const SKILLS = {
  sigil: {
    name: "Sigil",
    x: 0,
    y: 0,
    cost: 0,
    req: [],
    color: "#ffffff",
    desc: "Whatever sigil stats you have.",
  },

  // -----------------------------------------
  //                VITALITY
  // -----------------------------------------

  vitality: {
    name: "Vitality",
    x: -3,
    y: 0,
    cost: 1,
    req: ["sigil"],
    color: "#557a2e",
    desc: "Improves your base survivability and endurance.",
  },
  health_a: {
    name: "Health α",
    x: -5,
    y: 0,
    cost: 1,
    req: ["vitality"],
    color: "#557a2e",
    desc: "Increases maximum health.",
    stats: { Health: 2 },
  },
  health_b: {
    name: "Health β",
    x: -7,
    y: 0,
    cost: 1,
    req: ["health_a"],
    color: "#557a2e",
    desc: "Increases maximum health.",
    stats: { Health: 2 },
  },
  health_c: {
    name: "Health γ",
    x: -9,
    y: 0,
    cost: 1,
    req: ["health_b"],
    color: "#557a2e",
    desc: "Increases maximum health.",
    stats: { Health: 2 },
  },
  health_d: {
    name: "Health δ",
    x: -11,
    y: 0,
    cost: 1,
    req: ["health_c"],
    color: "#557a2e",
    desc: "Greatly increases max health.",
    stats: { Health: 2 },
  },
  health_e: {
    name: "Health ε",
    x: -13,
    y: 0,
    cost: 1,
    req: ["health_d"],
    color: "#557a2e",
    desc: "Massively increases max health.",
    stats: { Health: 2 },
  },
  iron_body: {
    name: "Iron Body",
    x: -15,
    y: 0,
    cost: 2,
    req: ["health_e"],
    color: "#557a2e",
    desc: "Become immune to injury and illness.",
    level: 40,
    abilities: ["Iron Body"],
  },

  coagulation: {
    name: "Coagulation",
    x: -13,
    y: -2,
    cost: 1,
    req: ["health_d"],
    color: "#4a7a2e",
    desc: "Incoming bleed damage is reduced.",
    abilities: ["Coagulation"],
  },

  saturation_a: {
    name: "Saturation α",
    x: -8,
    y: 2,
    cost: 1,
    req: ["health_b"],
    color: "#667b2e",
    desc: "Increase healing from Hunger.",
    stats: { "Health Regeneration %": 14 },
  },
  saturation_b: {
    name: "Saturation β",
    x: -10,
    y: 2,
    cost: 1,
    req: ["saturation_a"],
    color: "#667b2e",
    desc: "Increase healing from Hunger.",
    stats: { "Health Regeneration %": 14 },
  },
  saturation_c: {
    name: "Saturation γ",
    x: -12,
    y: 2,
    cost: 1,
    req: ["saturation_b"],
    color: "#667b2e",
    desc: "Increase healing from Hunger.",
    stats: { "Health Regeneration %": 14 },
  },

  // -----------------------------------------
  //           VITALITY + STRENGTH
  // -----------------------------------------

  sturdy_a: {
    name: "Sturdy α",
    x: -6,
    y: 3,
    cost: 1,
    req: ["health_a", "armsmaster_a"],
    color: "#767a2e",
    desc: "Increases posture.",
    stats: { "Posture Defense %": 8 },
  },
  sturdy_b: {
    name: "Sturdy β",
    x: -8,
    y: 4,
    cost: 1,
    req: ["sturdy_a"],
    color: "#767a2e",
    desc: "Increases posture.",
    stats: { "Posture Defense %": 8 },
  },
  sturdy_c: {
    name: "Sturdy γ",
    x: -10,
    y: 5,
    cost: 1,
    req: ["sturdy_b"],
    color: "#767a2e",
    desc: "Increases posture.",
    stats: { "Posture Defense %": 8 },
  },
  sturdy_d: {
    name: "Sturdy δ",
    x: -12,
    y: 6,
    cost: 1,
    req: ["sturdy_c"],
    color: "#767a2e",
    desc: "Increases posture.",
    stats: { "Posture Defense %": 8 },
  },
  unyielding_a: {
    name: "Unyielding α",
    x: -10,
    y: 7,
    cost: 1,
    req: ["sturdy_c"],
    color: "#5e5a25",
    desc: "If you are hit during a move, ignore that stun once.",
    abilities: ["Unyielding"],
  },
  unyielding_b: {
    name: "Unyielding β",
    x: -12,
    y: 8,
    cost: 1,
    req: ["unyielding_a"],
    color: "#5e5a25",
    desc: "If you are hit during a move, ignore that stun once.",
    abilities: ["Unyielding"],
  },

  // -----------------------------------------
  //                STRENGTH
  // -----------------------------------------

  strength: {
    name: "Strength",
    x: -2,
    y: 2,
    cost: 1,
    req: ["sigil"],
    color: "#8c7635",
    desc: "Increases physical force and melee impact.",
  },
  armsmaster_a: {
    name: "Armsmaster α",
    x: -4,
    y: 4,
    cost: 1,
    req: ["strength"],
    color: "#8c7635",
    desc: "Increases physical damage.",
    stats: { "Physical Damage %": 2 },
  },
  armsmaster_b: {
    name: "Armsmaster β",
    x: -6,
    y: 6,
    cost: 1,
    req: ["armsmaster_a"],
    color: "#8c7635",
    desc: "Increases physical damage.",
    stats: { "Physical Damage %": 2 },
  },
  armsmaster_c: {
    name: "Armsmaster γ",
    x: -8,
    y: 8,
    cost: 1,
    req: ["armsmaster_b"],
    color: "#8c7635",
    desc: "Increases physical damage.",
    stats: { "Physical Damage %": 2 },
  },
  armsmaster_d: {
    name: "Armsmaster δ",
    x: -10,
    y: 10,
    cost: 1,
    req: ["armsmaster_c"],
    color: "#8c7635",
    desc: "Increases physical damage.",
    stats: { "Physical Damage %": 2 },
  },
  backswing: {
    name: "Backswing",
    x: -12,
    y: 12,
    cost: 2,
    req: ["armsmaster_d"],
    color: "#8c7635",
    desc: "Your heavy attack can be used twice before it needs to recover.",
    level: 20,
    abilities: ["Backswing"],
  },
  ricochet_a: {
    name: "Ricochet α",
    x: -8,
    y: 10,
    cost: 2,
    req: ["armsmaster_d"],
    color: "#594522",
    desc: "Blocking or deflecting a bullet with a bladed weapon ricochets it away.",
    abilities: ["Ricochet"],
  },
  ricochet_b: {
    name: "Ricochet β",
    x: -9,
    y: 12,
    cost: 2,
    req: ["ricochet_a"],
    color: "#594522",
    desc: "Bullets deflected by a bladed weapon no longer have a cooldown.",
    abilities: ["Ricochet"],
  },

  // -----------------------------------------
  //          STRENGTH + PRESENCE
  // -----------------------------------------

  flurry: {
    name: "Flurry",
    x: -3,
    y: 6,
    cost: 1,
    req: ["armsmaster_a", "influence_a"],
    color: "#7b4f2e",
    desc: "Unleash a rapid triple strike.",
    abilities: ["Flurry"],
  },
  slayer_a: {
    name: "Slayer α",
    x: -4,
    y: 8,
    cost: 1,
    req: ["flurry"],
    color: "#7b4f2e",
    desc: "Increase your Monster Damage against monsters.",
    stats: { "Monster Damage %": 8 },
  },
  slayer_b: {
    name: "Slayer β",
    x: -5,
    y: 10,
    cost: 1,
    req: ["slayer_a"],
    color: "#7b4f2e",
    desc: "Increase your Monster Damage against monsters.",
    stats: { "Monster Damage %": 8 },
  },
  slayer_c: {
    name: "Slayer γ",
    x: -6,
    y: 12,
    cost: 1,
    req: ["slayer_b"],
    color: "#7b4f2e",
    desc: "Increase your Monster Damage against monsters.",
    stats: { "Monster Damage %": 8 },
  },

  // -----------------------------------------
  //                 PRESENCE
  // -----------------------------------------

  presence: {
    name: "Presence",
    x: 0,
    y: 3,
    cost: 1,
    req: ["sigil"],
    color: "#7b2e2e",
    desc: "A forceful reputation that lets you bend others through fear, authority, or renown.",
  },
  influence_a: {
    name: "Influence α",
    x: 0,
    y: 5,
    cost: 1,
    req: ["presence"],
    color: "#7b2e2e",
    desc: "Increase your notoriety multiplier.",
    stats: { "Notoriety Multiplier %": 5 },
  },
  influence_b: {
    name: "Influence β",
    x: 0,
    y: 7,
    cost: 1,
    req: ["influence_a"],
    color: "#7b2e2e",
    desc: "Increase your notoriety multiplier.",
    stats: { "Notoriety Multiplier %": 5 },
  },
  influence_c: {
    name: "Influence γ",
    x: 0,
    y: 9,
    cost: 1,
    req: ["influence_b"],
    color: "#7b2e2e",
    desc: "Increase your notoriety multiplier.",
    stats: { "Notoriety Multiplier %": 5 },
  },
  influence_d: {
    name: "Influence δ",
    x: 0,
    y: 11,
    cost: 1,
    req: ["influence_c"],
    color: "#7b2e2e",
    desc: "Increase your notoriety multiplier.",
    stats: { "Notoriety Multiplier %": 5 },
  },
  influence_e: {
    name: "Influence ε",
    x: 0,
    y: 13,
    cost: 1,
    req: ["influence_d"],
    color: "#7b2e2e",
    desc: "Increase your notoriety multiplier.",
    stats: { "Notoriety Multiplier %": 5 },
  },
  Command: {
    name: "Command",
    x: 0,
    y: 15,
    cost: 1,
    req: ["influence_e"],
    color: "#7b2e2e",
    desc: "Nearby enemies who fear your notoriety gain Fear. Fear: Lowers damage and movement speed.",
    abilities: ["Command"],
  },

  play_dead: {
    name: "Play Dead",
    x: 2,
    y: 13,
    cost: 1,
    req: ["influence_e"],
    color: "#5c232c",
    desc: "Feign death. Unlocks the Play Dead gesture.",
    abilities: ["Play Dead"],
  },
  chant: {
    name: "Chant",
    x: -2,
    y: 13,
    cost: 1,
    req: ["influence_e"],
    color: "#5c2c23",
    desc: "A battle cry that provides a motivation buff to you and nearby allies.",
    abilities: ["Chant"],
  },

  point_location: {
    name: "Point Location",
    x: -2,
    y: 9,
    cost: 1,
    req: ["influence_c"],
    color: "#5c2f23",
    desc: "Using Point pings your cursor location for you, teammates, and guildmates.",
    abilities: ["Point"],
  },
  shout_message: {
    name: "Shout Message",
    x: -3,
    y: 11,
    cost: 1,
    req: ["point_location"],
    color: "#5c2f23",
    desc: "Allows you to shout messages to other players in your vicinity.",
    abilities: ["Shout"],
  },
  taunt_enemy: {
    name: "Taunt Enemy",
    x: -4,
    y: 13,
    cost: 1,
    req: ["shout_message"],
    color: "#5c2f23",
    desc: "Aggros mobs in front of you. Extremely useful for tank-oriented builds to manage enemy focus.",
    abilities: ["Taunt"],
  },

  // -----------------------------------------
  //            PRESENCE + SOUL
  // -----------------------------------------

  perception_a: {
    name: "Perception α",
    x: 3,
    y: 6,
    cost: 1,
    req: ["influence_a", "essence_a"],
    color: "#762c4c",
    desc: "Increases distortion resistance.",
    stats: { "Distortion Resistance %": 10 },
  },
  perception_b: {
    name: "Perception β",
    x: 4,
    y: 8,
    cost: 1,
    req: ["perception_a"],
    color: "#762c4c",
    desc: "Increases distortion resistance.",
    stats: { "Distortion Resistance %": 10 },
  },
  perception_c: {
    name: "Perception γ",
    x: 5,
    y: 10,
    cost: 1,
    req: ["perception_b"],
    color: "#762c4c",
    desc: "Increases distortion resistance.",
    stats: { "Distortion Resistance %": 10 },
  },
  perception_d: {
    name: "Perception δ",
    x: 6,
    y: 12,
    cost: 1,
    req: ["perception_c"],
    color: "#762c4c",
    desc: "Increases distortion resistance.",
    stats: { "Distortion Resistance %": 10 },
  },
  deep_wound: {
    name: "Deep Wound",
    x: 8,
    y: 11,
    cost: 1,
    req: ["perception_d"],
    color: "#762c4c",
    desc: "Your weapon attacks now inflict anti-heal for 8 seconds, nullifying your opponents healing.",
    abilities: ["Deep Wound"],
  },

  benediction_a: {
    name: "Benediction α",
    x: 2,
    y: 9,
    cost: 1,
    req: ["perception_b"],
    color: "#762c4c",
    desc: "Increases incoming and outgoing healing.",
    stats: { "Incoming Healing %": 10, "Outgoing Healing %": 10 },
  },
  benediction_b: {
    name: "Benediction β",
    x: 3,
    y: 11,
    cost: 1,
    req: ["benediction_a"],
    color: "#762c4c",
    desc: "Increases incoming and outgoing healing.",
    stats: { "Incoming Healing %": 10, "Outgoing Healing %": 10 },
  },
  merc_command: {
    name: "Merciful Command",
    x: 4,
    y: 13,
    cost: 1,
    req: ["benediction_b"],
    color: "#762c4c",
    desc: "When inflicting Command to an enemy below half health, increase its duration.",
    abilities: ["Merciful Command"],
  },

  // -----------------------------------------
  //                  SOUL
  // -----------------------------------------

  soul: {
    name: "Soul",
    x: 2,
    y: 2,
    cost: 1,
    req: ["sigil"],
    color: "#7b2e67",
    desc: "Deepens your soul reserve and resistance to soul drain.",
  },
  essence_a: {
    name: "Essence α",
    x: 4,
    y: 4,
    cost: 1,
    req: ["soul"],
    color: "#7b2e67",
    desc: "Increase your Essence.",
    stats: { "Soul %": 10 },
  },
  essence_b: {
    name: "Essence β",
    x: 6,
    y: 6,
    cost: 1,
    req: ["essence_a"],
    color: "#7b2e67",
    desc: "Increase your Essence.",
    stats: { "Soul %": 10 },
  },
  essence_c: {
    name: "Essence γ",
    x: 8,
    y: 8,
    cost: 1,
    req: ["essence_b"],
    color: "#7b2e67",
    desc: "Increase your Essence.",
    stats: { "Soul %": 10 },
  },
  essence_d: {
    name: "Essence δ",
    x: 10,
    y: 10,
    cost: 1,
    req: ["essence_c"],
    color: "#7b2e67",
    desc: "Increase your Essence.",
    stats: { "Soul %": 10 },
  },
  soul_drive: {
    name: "Soul Drive",
    x: 12,
    y: 12,
    cost: 1,
    req: ["essence_d"],
    color: "#7b2e67",
    desc: "Executing someone creates far more experience wisps, without increasing total experience gained.",
    abilities: ["Sould Drive"],
  },
  soul_shield: {
    name: "Soul Shield",
    x: 14,
    y: 11,
    cost: 2,
    req: ["soul_drive"],
    color: "#692861",
    desc: "Burnaway wisps grant their full healing as shield for longer when collected at full health.",
    level: 25,
    abilities: ["Sould Shield"],
  },
  soul_reaper: {
    name: "Soul Reaper",
    x: 15,
    y: 9,
    cost: 2,
    req: ["soul_shield"],
    color: "#5c225a",
    desc: "Killing an enemy greatly shortens the recovery of all tool skills.",
    level: 35,
    abilities: ["Sould Reaper"],
  },

  // -----------------------------------------
  //             SOUL + DEXTERITY
  // -----------------------------------------

  sleight_a: {
    name: "Sleight α",
    x: 6,
    y: 3,
    cost: 1,
    req: ["essence_a", "prof_a"],
    color: "#602563",
    desc: "Widens skill check windows.",
    stats: { "Skill Check Window %": 4 },
  },
  sleight_b: {
    name: "Sleight β",
    x: 8,
    y: 4,
    cost: 1,
    req: ["sleight_a"],
    color: "#602563",
    desc: "Widens skill check windows.",
    stats: { "Skill Check Window %": 4 },
  },
  sleight_c: {
    name: "Sleight γ",
    x: 10,
    y: 5,
    cost: 1,
    req: ["sleight_b"],
    color: "#602563",
    desc: "Widens skill check windows.",
    stats: { "Skill Check Window %": 4 },
  },
  sleight_d: {
    name: "Sleight δ",
    x: 12,
    y: 6,
    cost: 1,
    req: ["sleight_c"],
    color: "#602563",
    desc: "Widens skill check windows.",
    stats: { "Skill Check Window %": 4 },
  },
  sleight_e: {
    name: "Sleight ε",
    x: 14,
    y: 7,
    cost: 1,
    req: ["sleight_d"],
    color: "#602563",
    desc: "Widens skill check windows.",
    level: 50,
    stats: { "Skill Check Window %": 4 },
  },

  phase_a: {
    name: "Phase Reflex α",
    x: 13,
    y: 4,
    cost: 2,
    req: ["sleight_d"],
    color: "#602563",
    desc: "Automatically evades incoming attacks for 6 seconds.",
    level: 30,
    abilities: ["Phase Reflex"],
  },
  phase_b: {
    name: "Phase Reflex α",
    x: 15,
    y: 5,
    cost: 2,
    req: ["phase_a"],
    color: "#602563",
    level: 40,
    desc: "Automatically evades incoming attacks for 9 seconds.",
    abilities: ["Phase Reflex"],
  },

  // -----------------------------------------
  //                DEXTERITY
  // -----------------------------------------

  dexterity: {
    name: "Dexterity",
    x: 3,
    y: 0,
    cost: 1,
    req: ["sigil"],
    color: "#542e7b",
    desc: "Refines precision, handling speed, and timing-based actions.",
  },
  prof_a: {
    name: "Proficiency α",
    x: 5,
    y: 0,
    cost: 1,
    req: ["dexterity"],
    color: "#542e7b",
    desc: "Shorten skill recovery.",
    stats: { "Cooldown Reduction %": 2 },
  },
  prof_b: {
    name: "Proficiency β",
    x: 7,
    y: 0,
    cost: 1,
    req: ["prof_a"],
    color: "#542e7b",
    desc: "Shorten skill recovery.",
    stats: { "Cooldown Reduction %": 2 },
  },
  prof_c: {
    name: "Proficiency γ",
    x: 9,
    y: 0,
    cost: 1,
    req: ["prof_b"],
    color: "#542e7b",
    desc: "Shorten skill recovery.",
    stats: { "Cooldown Reduction %": 2 },
  },
  prof_d: {
    name: "Proficiency δ",
    x: 11,
    y: 0,
    cost: 1,
    req: ["prof_c"],
    color: "#542e7b",
    desc: "Shorten skill recovery.",
    stats: { "Cooldown Reduction %": 2 },
  },
  prof_e: {
    name: "Proficiency ε",
    x: 13,
    y: 0,
    cost: 1,
    req: ["prof_d"],
    color: "#542e7b",
    desc: "Shorten skill recovery.",
    stats: { "Cooldown Reduction %": 2 },
  },
  comp_guard: {
    name: "Compromised Guard",
    x: 15,
    y: 0,
    cost: 2,
    req: ["prof_e"],
    color: "#542e7b",
    desc: "Nil",
    level: "???",
    abilities: ["Compromised Guard"],
  },

  catfall_a: {
    name: "Catfall α",
    x: 11,
    y: -2,
    cost: 1,
    req: ["prof_d"],
    color: "#402b6d",
    desc: "Reduce fall damage.",
    stats: { "Fall Damage Reduction %": 20 },
  },
  catfall_b: {
    name: "Catfall α",
    x: 13,
    y: -2,
    cost: 1,
    req: ["catfall_a"],
    color: "#402b6d",
    desc: "Reduce fall damage.",
    stats: { "Fall Damage Reduction %": 20 },
  },
  soft_land: {
    name: "Soft Landing",
    x: 15,
    y: -2,
    cost: 1,
    req: ["catfall_b"],
    color: "#402b6d",
    desc: "Fall damage no longer causes fall stagger or stun unless the fall is strong enough to ragdoll you.",
    abilities: ["Soft Landing"],
  },

  deflect_a: {
    name: "Deflect α",
    x: 9,
    y: 2,
    cost: 2,
    req: ["prof_c"],
    color: "#652e7b",
    desc: "Automatically block the next incoming attack",
    level: 10,
    abilities: ["Deflect"],
  },
  deflect_b: {
    name: "Deflect β",
    x: 11,
    y: 2,
    cost: 2,
    req: ["deflect_a"],
    color: "#652e7b",
    desc: "Automatically block the next incoming attack",
    level: 20,
    abilities: ["Deflect"],
  },
  deflect_c: {
    name: "Deflect γ",
    x: 13,
    y: 2,
    cost: 2,
    req: ["deflect_b"],
    color: "#652e7b",
    desc: "Automatically block the next incoming attack",
    level: 30,
    abilities: ["Deflect"],
  },

  // -----------------------------------------
  //           DEXTERITY + AGILITY
  // -----------------------------------------

  clamber: {
    name: "Clamber",
    x: 6,
    y: -2,
    cost: 1,
    req: ["prof_a", "mobility_a"],
    color: "#3b2d77",
    desc: "Press Q to dash swiftly across walls and ledges.",
    abilities: ["Clamber"],
  },
  climb_a: {
    name: "Climb α",
    x: 8,
    y: -3,
    cost: 1,
    req: ["clamber"],
    color: "#3b2d77",
    desc: "Improves climb speed and stamina.",
  },
  climb_b: {
    name: "Climb β",
    x: 10,
    y: -4,
    cost: 1,
    req: ["climb_a"],
    color: "#3b2d77",
    desc: "Improves climb speed and stamina.",
    stats: { "Climb Speed %": 20, "Climb Stamina %": 100 },
  },
  climb_c: {
    name: "Climb γ",
    x: 12,
    y: -5,
    cost: 1,
    req: ["climb_b"],
    color: "#3b2d77",
    desc: "Improves climb speed and stamina.",
    stats: { "Climb Speed %": 20, "Climb Stamina %": 100 },
  },

  // -----------------------------------------
  //                AGILITY
  // -----------------------------------------

  agility: {
    name: "Agility",
    x: 2,
    y: -2,
    cost: 1,
    req: ["sigil"],
    color: "#324683",
    desc: "Improves movement control and evasive responsiveness.",
  },
  mobility_a: {
    name: "Mobility α",
    x: 4,
    y: -4,
    cost: 1,
    req: ["agility"],
    color: "#324683",
    desc: "Increases sprint power.",
    stats: { "Sprint Power %": 5 },
  },
  mobility_b: {
    name: "Mobility β",
    x: 6,
    y: -6,
    cost: 1,
    req: ["mobility_a"],
    color: "#324683",
    desc: "Increases sprint power.",
    stats: { "Sprint Power %": 5 },
  },
  mobility_c: {
    name: "Mobility γ",
    x: 8,
    y: -8,
    cost: 1,
    req: ["mobility_b"],
    color: "#324683",
    desc: "Increases sprint power.",
    stats: { "Sprint Power %": 5 },
  },
  mobility_d: {
    name: "Mobility δ",
    x: 10,
    y: -10,
    cost: 1,
    req: ["mobility_c"],
    color: "#324683",
    desc: "Increases sprint power.",
    stats: { "Sprint Power %": 5 },
  },
  mobility_e: {
    name: "Mobility ε",
    x: 12,
    y: -12,
    cost: 1,
    req: ["mobility_d"],
    color: "#324683",
    desc: "Increases sprint power.",
    stats: { "Sprint Power %": 5 },
  },
  fleetfoot: {
    name: "Fleetfoot",
    x: 6,
    y: -8,
    cost: 2,
    req: ["mobility_c"],
    color: "#1966a8",
    desc: "Dodging an attack boosts your movement speed briefly.",
    level: 25,
    abilities: ["Fleetfoot"],
  },
  footwork: {
    name: "Footwork",
    x: 8,
    y: -10,
    cost: 2,
    req: ["fleetfoot"],
    color: "#1966a8",
    desc: "If you dodge an attack with Dash or Roll, you can use Dash or Roll again immediately.",
    level: 25,
    abilities: ["Footwork"],
  },
  clamber_mob: {
    name: "Clamber",
    x: 8,
    y: -6,
    cost: 1,
    req: ["mobility_b"],
    color: "#232a5c",
    desc: "Terragen race exclusive.<br>Press Q to dash swiftly across walls and ledges.",
  },
  lightfooted: {
    name: "LightFooted",
    x: 10,
    y: -8,
    cost: 1,
    req: ["clamber_mob"],
    color: "#232a5c",
    desc: "Nil",
  },

  // -----------------------------------------
  //            AGILITY + ARCANA
  // -----------------------------------------

  water_walk: {
    name: "Water Walk",
    x: 3,
    y: -6,
    cost: 1,
    req: ["mobility_a", "prowess_a"],
    color: "#1f5e94",
    desc: "Walk effortlessly atop any body of water.",
    abilities: ["Water Walk"],
  },
  phase_run_a: {
    name: "Phase Run α",
    x: 4,
    y: -8,
    cost: 2,
    req: ["water_walk"],
    color: "#1f5e94",
    desc: "Charge Mana to super sprint while out of combat.",
    level: 20,
    abilities: ["Phase Run"],
  },
  phase_run_b: {
    name: "Phase Run β",
    x: 5,
    y: -10,
    cost: 2,
    req: ["phase_run_a"],
    color: "#1f5e94",
    desc: "Charge Mana to super sprint while out of combat.",
    level: 30,
    abilities: ["Phase Run"],
  },
  phase_dash: {
    name: "Phase Dash",
    x: 4,
    y: -12,
    cost: 2,
    req: ["phase_run_b", "flux_b"],
    color: "#32717e",
    desc: "Nil",
    abilities: ["Phase Dash"],
  },

  // -----------------------------------------
  //                ARCANA
  // -----------------------------------------

  arcana: {
    name: "Arcana",
    x: 0,
    y: -3,
    cost: 1,
    req: ["sigil"],
    color: "#348585",
    desc: "Hold G to channel and recharge your Magicka.",
  },
  prowess_a: {
    name: "Prowess α",
    x: 0,
    y: -5,
    cost: 1,
    req: ["arcana"],
    color: "#348585",
    desc: "Increases magical damage.",
    stats: { "Magical Damage %": 2 },
  },
  prowess_b: {
    name: "Prowess β",
    x: 0,
    y: -7,
    cost: 1,
    req: ["prowess_a"],
    color: "#348585",
    desc: "Increases magical damage.",
    stats: { "Magical Damage %": 2 },
  },
  prowess_c: {
    name: "Prowess γ",
    x: 0,
    y: -9,
    cost: 1,
    req: ["prowess_b"],
    color: "#348585",
    desc: "Increases magical damage.",
    stats: { "Magical Damage %": 2 },
  },
  prowess_d: {
    name: "Prowess δ",
    x: 0,
    y: -11,
    cost: 1,
    req: ["prowess_c"],
    color: "#348585",
    desc: "Increases magical damage.",
    stats: { "Magical Damage %": 2 },
  },
  prowess_e: {
    name: "Prowess ε",
    x: 0,
    y: -13,
    cost: 1,
    req: ["prowess_d"],
    color: "#348585",
    desc: "Increases magical damage.",
    stats: { "Magical Damage %": 2 },
  },

  flux_a: {
    name: "Flux α",
    x: 2,
    y: -9,
    cost: 1,
    req: ["prowess_b"],
    color: "#32717e",
    desc: "Increases magicka regeneration rate.",
    stats: { "Magicka Regeneration %": 25 },
  },
  flux_b: {
    name: "Flux β",
    x: 2,
    y: -11,
    cost: 1,
    req: ["flux_a"],
    color: "#32717e",
    desc: "Increases magicka regeneration rate.",
    stats: { "Magicka Regeneration %": 25 },
  },
  flux_y: {
    name: "Flux γ",
    x: 2,
    y: -13,
    cost: 1,
    req: ["flux_b"],
    color: "#32717e",
    desc: "Increases magicka regeneration rate.",
    stats: { "Magicka Regeneration %": 25 },
  },

  ward_a: {
    name: "Spell Ward α",
    x: -2,
    y: -9,
    cost: 1,
    req: ["prowess_b"],
    color: "#245a4f",
    desc: "Increases resistance to fire and magic.",
    stats: { "Fire Resistance %": 14, "Magical Defense %": 5 },
  },
  ward_b: {
    name: "Spell Ward β",
    x: -2,
    y: -11,
    cost: 1,
    req: ["ward_a"],
    color: "#245a4f",
    desc: "Increases resistance to fire and magic.",
    stats: { "Fire Resistance %": 14, "Magical Defense %": 5 },
  },
  ward_c: {
    name: "Spell Ward γ",
    x: -2,
    y: -13,
    cost: 1,
    req: ["ward_b"],
    color: "#245a4f",
    desc: "Increases resistance to fire and magic.",
    stats: { "Fire Resistance %": 14, "Magical Defense %": 5 },
  },

  archmage: {
    name: "Archmage",
    x: 0,
    y: -15,
    cost: 2,
    req: ["prowess_e", "flux_y", "ward_c"],
    color: "#348585",
    desc: "Your next mage skill autocasts and ignores the global spell lockout.",
    level: 40,
    stats: { "Magical Damage %": 5 },
  },

  // -----------------------------------------
  //           ARCANA + WILLPOWER
  // -----------------------------------------

  spellshield_a: {
    name: "Spellshield α",
    x: -3,
    y: -6,
    cost: 1,
    req: ["prowess_a", "resolve_a"],
    color: "#338661",
    desc: "Hold block and charge Magicka to cast Spellshield.",
    abilities: ["Spellshield"],
  },
  spellshield_b: {
    name: "Spellshield β",
    x: -4,
    y: -8,
    cost: 1,
    req: ["spellshield_a"],
    color: "#338661",
    desc: "Magicka drains slower while in Spellshield.",
  },

  mana_body_a: {
    name: "Mana Body α",
    x: -5,
    y: -10,
    cost: 2,
    req: ["spellshield_b"],
    color: "#338661",
    desc: "Press E above 80% Magicka to spend 80% and mantle your arms in mana, enhancing weapon damage and allowing spellshielding without charging mana. Charge back to 80% and press E again to turn it off.",
    level: 30,
    abilities: ["Mana Body"],
  },
  mana_body_b: {
    name: "Mana Body β",
    x: -4,
    y: -12,
    cost: 2,
    req: ["mana_body_a", "ward_b"],
    color: "#245a4f",
    desc: "Press E above 80% Magicka to spend 80% and mantle your body in mana, enhancing weapon damage and allowing spellshielding without charging mana. Charge back to 80% and press E again to turn it off.",
    level: 40,
    abilities: ["Mana Body"],
  },

  // -----------------------------------------
  //                WILLPOWER
  // -----------------------------------------

  willpower: {
    name: "Willpower",
    x: -2,
    y: -2,
    cost: 1,
    req: ["sigil"],
    color: "#338548",
    desc: "Bolsters mental resolve against pressure and disruption.",
  },
  resolve_a: {
    name: "Resolve α",
    x: -4,
    y: -4,
    cost: 1,
    req: ["willpower"],
    color: "#338548",
    desc: "Increase your physical and magical defense.",
    stats: { "Physical Defense %": 2, "Magical Defense %": 2 },
  },
  resolve_b: {
    name: "Resolve β",
    x: -6,
    y: -6,
    cost: 1,
    req: ["resolve_a"],
    color: "#338548",
    desc: "Increase your physical and magical defense.",
    stats: { "Physical Defense %": 2, "Magical Defense %": 2 },
  },
  resolve_c: {
    name: "Resolve γ",
    x: -8,
    y: -8,
    cost: 1,
    req: ["resolve_b"],
    color: "#338548",
    desc: "Increase your physical and magical defense.",
    stats: { "Physical Defense %": 2, "Magical Defense %": 2 },
  },
  resolve_d: {
    name: "Resolve δ",
    x: -10,
    y: -10,
    cost: 1,
    req: ["resolve_c"],
    color: "#338548",
    desc: "Increase your physical and magical defense.",
    stats: { "Physical Defense %": 2, "Magical Defense %": 2 },
  },
  resolve_e: {
    name: "Resolve ε",
    x: -12,
    y: -12,
    cost: 1,
    req: ["resolve_d"],
    color: "#338548",
    desc: "Increase your physical and magical defense.",
    stats: { "Physical Defense %": 2, "Magical Defense %": 2 },
  },
  sheer_will: {
    name: "Sheer Will",
    x: -14,
    y: -10,
    cost: 1,
    req: ["resolve_e"],
    color: "#338537",
    desc: "Survive what would be a fatal attack at 1 HP.",
    abilities: ["Sheer Will"],
  },
  last_stand: {
    name: "Last Stand",
    x: -12,
    y: -8,
    cost: 2,
    req: ["sheer_will"],
    color: "#338537",
    level: 40,
    desc: "When an incoming hit would knock you, become immune to knockdown for 6 seconds, but suffer a temporary debuff.",
    abilities: ["Last Stand"],
  },
  self_rec: {
    name: "Self Recovery",
    x: -8,
    y: -12,
    cost: 1,
    req: ["resolve_d"],
    color: "#338548",
    level: 40,
    desc: "Able to pick yourself up from being knocked.",
    abilities: ["Self Recovery"],
  },

  // -----------------------------------------
  //          WILLPOWER + VITALITY
  // -----------------------------------------

  tox_a: {
    name: "Toxicity Res α",
    x: -6,
    y: -2,
    cost: 1,
    req: ["health_a", "resolve_a"],
    color: "#356e29",
    desc: "Reduces toxicity buildup.",
    stats: { "Toxicity Resistance %": 10 },
  },
  tox_b: {
    name: "Toxicity Res β",
    x: -8,
    y: -4,
    cost: 1,
    req: ["tox_a"],
    color: "#356e29",
    desc: "Reduces toxicity buildup.",
    stats: { "Toxicity Resistance %": 10 },
  },
  tox_c: {
    name: "Toxicity Res γ",
    x: -10,
    y: -2,
    cost: 1,
    req: ["tox_b"],
    color: "#3f6c29",
    desc: "Reduces toxicity buildup.",
    stats: { "Toxicity Resistance %": 10 },
  },
  tox_d: {
    name: "Toxicity Res δ",
    x: -12,
    y: -4,
    cost: 1,
    req: ["tox_c"],
    color: "#356e29",
    desc: "Reduces toxicity buildup.",
    stats: { "Toxicity Resistance %": 10 },
  },
  cannibal: {
    name: "Cannibal",
    x: -14,
    y: -6,
    cost: 1,
    req: ["tox_d"],
    color: "#356e29",
    desc: "Forgo your humanity and gain the ability to eat people instead of gripping them, restoring your hunger.",
    abilities: ["Cannibal"],
  },
  survivor: {
    name: "Survivor",
    x: -10,
    y: -6,
    cost: 1,
    req: ["resolve_c", "tox_b"],
    color: "#4a7a2e",
    desc: "Increase HP recovered when you are revived.",
  },
};
